### ISSUE TITLE
License: Apache 2.0 instead of GPL?

### ISSUE THREAD

**Issue by chrzyki** [clld/clts#7]
Hey,

currently, the repo/project is using the GNU GPL 3 - is that correct/intended?

**Comment by LinguList** [comment]
yes, is there a problem with that?

**Comment by LinguList** [comment]
i mean: I don't care, but I like the GPL as a general principle...

**Comment by LinguList** [comment]
Although I don't really know what it means in the end, and I know other people use other licenses.

**Comment by xrotwang** [comment]
I typically use Apache 2, because that's the license of clld as well. And it's the license for clld, because most of the javascript stuff which is distributed with clld, is Apache 2 licensed as well.

So basically, I try to minimize the cognitive effort required by people who want to re-use the software.

**Comment by LinguList** [comment]
Okay, I don't have a problem with changing the license, so going for Apache 2 is fine by me.

**Comment by chrzyki** [comment]
Closed in https://github.com/clld/clts/commit/b81e5ac3036362ad27b97a5dd54cb3ffc3a7f331.
